### ISSUE TITLE
telegram客户端不能联网

### ISSUE THREAD

**Issue by tsiupokleung** [petronny/gfwlist2pac#1]
我用的是telegram免安装版，启用了pac模式之后就它不能联网了，其他网页浏览正常

**Comment by petronny** [comment]
1. 我不知道你用的什么环境
1. 我不知道这个“启用pac模式”是哪个软件提供的
1. 我不知道你的vpn配置是否正常
1. 我不知道你用的telegram配置是否正常
1. 请判断这个是gfwlist的问题还是genpac的问题还是这个repo的问题
1. 请阅读《提问的智慧》

执行以上步骤后，如仍有问题，请在此回复。

**Comment by snafumeander** [comment]
躺枪系列。。。我为什么会收到这种邮件
