### ISSUE TITLE
iqiyi.com咋跑代理里面去了

### ISSUE THREAD

**Issue by leosam2048** [petronny/gfwlist2pac#7]
![image](https://user-images.githubusercontent.com/19237423/101718257-cad2e600-3adb-11eb-8789-bcbe3b0b4ff3.png)

**Comment by dodois** [comment]
@leosam2048 
智能模式即pac模式，采用开源仓库维护的 GFWList 数据，注释保留了出处信息
/**
 * genpac 2.1.0 https://github.com/JinnLynn/genpac
 * GFWList Last-Modified: 2020-11-13 22:48:07
 */

**Comment by petronny** [comment]
a8a1524d99fea4e7d302dc33d6c35ee11764d075
生成自 https://github.com/gfwlist/gfwlist/commit/e84a085e7575d2e4f8c4b7027dc4d9ef8216746a
关联至 https://github.com/gfwlist/gfwlist/issues/1311 https://github.com/gfwlist/gfwlist/issues/1182

如有疑问请至 https://github.com/gfwlist/gfwlist 反馈
